### ISSUE TITLE
idea

### ISSUE THREAD

**Issue by eunaumtenhoid** [AlfredoRamos/phpbb-ext-hide#1]
HIDE only for guests?
it is possible to hide only appear for those who respond or thank the topic
compatible with thanks for post?
add group permission to view the hide like administrators? In other words you want to disable the hide bbcode for specific groups

like ext adb >> https://github.com/marcovo/phpbb_hidebbcode

**Comment by AlfredoRamos** [comment]
Hi,

Yes, it only hides content to guests, and I have no plans to add more features for now.

This extension is for self use only, It won't be posted on the official forum nor be sent for validation, so you might want to use another `hide` extension.
